<a href="https://colab.research.google.com/github/roshan-koirala/ceri8211globalgeophysics/blob/master/Roshan_HW5_Q4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modules**

In [0]:
import numpy as np
import math as m

**Parameters for the selected plates**

The plate boundary points and the Rotation Plate are paired as:

(Plate Boundary Points)  = (Rotation Pole)
1. Himalaya = India - Eurasia
2. S.Chile Trench    =  Nazca - South America
3. San Andreas = Cocos - North America
4. W. Aleutian Trench = Eurasia - Pacific
5. Java = India - Eurasia

In [0]:
R = 6371*1e5   # Radius of earth in cm

# latitude of point x at plate boundary in radian
lat_x = (np.pi/180) * np.array([35, -35, 38, 54, -12]) 

# longitude of point x in degrees at plate boundary in radian
lon_x = (np.pi/180) * np.array([72, -74, -122, 169, 120])

# latitude of rotation pole P in radian
lat_p = (np.pi/180) * np.array([24.4, 56, 27.9, 61.1, 24.4])

# longitude of rotation pole P in radian
lon_p = (np.pi/180) * np.array([17.7, -94, -120.7, -85.8, 17.7])

# Angular velocity of rotaion pole
omega = 1e-7 * np.array([5.1, 7.2, 13.6, 8.6, 5.1])

**Defining functions for calculation**

In [0]:
def fct_a ( lat_x, lon_x, lat_p, lon_p ):
    """
        lat_x: latitude of point x 
        lon_x: longitude of point x
        lat_p: latitude of rotation pole P 
        lon_p: longitude of roation pole P 
     """
    return m.acos(np.sin(lat_x) * np.sin(lat_p) + np.cos(lat_x) * np.cos(lat_p) * np.cos(lon_p-lon_x))

#=====================================================================================================
def fct_C ( lat_x, lon_x, lat_p, lon_p, a):
    """
        lat_x: latitude of point x 
        lon_x: longitude of point x
        lat_p: latitude of rotation pole P 
        lon_p: longitude of roation pole P 
        a    : Output of fct_a
    """
    return m.asin((np.cos(lat_p) * np.sin(lon_p-lon_x)) / np.sin(a))

#===================================================================
def fct_velocity (omega, R, a):
      """
        omega: angular velocity of the pole
        R    : Radius of earth
        a    : Output of fct_a
      """    
      return omega * R * (m.sin(a))

**Computation**

In [0]:
a = np.zeros( len( lat_x))
C = np.zeros( len( lat_x))
velocity = np.zeros( len( lat_x))
Beta = np.zeros( len( lat_x))

for i in range( len( lat_x)):
    a[i] = fct_a (lat_x[i], lon_x[i], lat_p[i], lon_p[i] )      # a in radian
    C[i] = fct_C( lat_x[i], lon_x[i], lat_p[i], lon_p[i], a[i]) # c in radian
    velocity[i] = (np.pi/180) * fct_velocity( omega[i], R, a[i])       # velociity in cm/yr
    Beta[i] = np.pi/2 + C[i]                                        # Azimuth of velocity vector

**Output**

In [0]:
print('Value a are:')
a  = 180/np.pi * a
print(a)

print('Value c are:')
C  = 180/np.pi * C
print(C)

print('Velocity (cm/yr) for above five plates are:')
#velocity = velocity
print(velocity)

print('Azimuth of above plates from North are:')
Azimuth  = 180/np.pi * Beta
print(Azimuth)



Value a are:
[ 47.75811732  92.58359997  10.15839785  50.66995452 106.00093814]
Value c are:
[-87.39986894 -11.03740749   6.52767045  37.08043356 -67.76527161]
Velocity (cm/yr) for above five plates are:
[4.19827367 7.99789669 2.66715822 7.39687386 5.45123302]
Azimuth of above plates from North are:
[  2.60013106  78.96259251  96.52767045 127.08043356  22.23472839]
